# Generated by Django 4.2.3 on 2023-07-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo_usuario', models.CharField(max_length=50)),
                ('contrasena_usuario', models.CharField(max_length=30)),
            ],
        ),
    ]
